apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
spec:
  resources:
    requests:
      storage: 50Mi
  storageClassName: glusterfile
  accessModes:
    - ReadWriteOnce
